### ISSUE TITLE
API Gateway integration - 5xx Error

### ISSUE THREAD

**Issue by iNDicat0r** [eawsy/aws-lambda-go-shim#10]
I have managed to deploy the hello world example. However i would like to integrate the lambda with API Gateway. I have created my API gateway method and choose the golang lambda function but i get "message": "Internal server error" when i call the http endpoint from postman.

**Comment by fsenart** [comment]
@iNDicat0r have you tried the integrated solution we provide (https://github.com/eawsy/aws-lambda-go-net) for API Gateway using this shim?

**Comment by iNDicat0r** [comment]
Thanks I wasn't aware of this(Needs proper documentation). A quick question, why is the handlers size that big ?

**Comment by fsenart** [comment]
Because of golang/go#17150 :smile:
