### ISSUE TITLE
Deployment size (shim)

### ISSUE THREAD

**Issue by iNDicat0r** [eawsy/aws-lambda-go-shim#17]
Hi

Can we do anything about the deployment size, at least decrease it? It seems too weird for me to see 8MB of code for a single hello world lambda function.

Regards

**Comment by fsenart** [comment]
Hi @iNDicat0r,
Have you updated your Docker image in the past days? We've updated the packaging script and you should have a package size of roughly 1.6MB for a simple function and complex ones should not exceed 4 or 5MB.

**Comment by fsenart** [comment]
PS: there is also another improvement available (1.6MB -> 700KB) but it has to be supported by AWS.
https://twitter.com/fsenart/status/856479105801494528

**Comment by iNDicat0r** [comment]
Ok you are right, i have to update the image:) lambda supports python3.6 and i am wondering if any time soon there will be an official golang support:/
