### ISSUE TITLE
Building in Fedora 26 fails.

### ISSUE THREAD

**Issue by zkanda** [eawsy/aws-lambda-go-shim#26]
Hello again,

I'm trying this project in a Fedora distro however when invoking `make` it fails on me, I'm trying to debug but I'm not sure whats going on, creating this issue here if anyone run into this too.

To reproduce, you just need to follow the tutorial: https://github.com/eawsy/aws-lambda-go-shim#quick-hands-on
Here's the log:
```
$ make
make: stat: Makefile: Permission denied
make: *** No rule to make target `all'.  Stop.
make: *** [Makefile:11: docker] Error 2
```

I already tried to change the permission of `Makefile` to 777 but still doesn't work.

**Comment by fsenart** [comment]
Hi @zkanda,
can you please confirm that your Docker daemon runs correctly `docker run --rm hello-world` and you have correct permissions on the current directory `ls -la`.

**Comment by zkanda** [comment]
@fsenart yes I can verify that:
```
[zkanda@localhost test]$  docker run --rm hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

[zkanda@localhost test]$ ls -la
total 20
drwxrwxr-x. 2 zkanda zkanda 4096 Jul  6 11:14 .
drwxrwxr-x. 5 zkanda zkanda 4096 Jul  6 11:10 ..
-rw-rw-r--. 1 zkanda zkanda  211 Jul  6 11:14 main.go
-rw-rw-r--. 1 zkanda zkanda 2287 Jul  6 11:11 Makefile
```

I tried our project too but it failed with permission issue. It seems to be a problem with the volumes are mounted, though I installed docker directly from fedora repos because the repo from Docker is not yet available for Fedora 26, I'm currently waiting for https://github.com/docker/for-linux/issues/35 and see if that would fix the problem.

**Comment by fsenart** [comment]
Ok, I'll keep the issue open until the Docker repo becomes available for F26 so you can retry your installation. 
PS: I've browsed a few issues related to mounted volumes and permission problems and it seems to be very related to selinux. You may disable selinux temporarily in order to evaluate its impact.

**Comment by zkanda** [comment]
Holy! yes, that solves it indeed. Urghhh, I wish I knew that before. Thanks for the solution @fsenart, appreciate it a lot. :joy:

Closing this as it resolve the issue.

Resolution: Just disable selinux for now, until you know how to play nice with it. :)
