### ISSUE TITLE
Use a custom Marshaler

### ISSUE THREAD

**Issue by ashinohara** [eawsy/aws-lambda-go-shim#30]
I would like to be able to return protobuf marshaled as json back from the `Handle` function.  I know that the current handler calls `json.Marshal` on the value returned from the lambda.  Is there a way to easily override this behavior and use the json marshaler in protobufs instead?

**Comment by fsenart** [comment]
Hi @ashinohara,
As you've noticed any value returned by the Handler is marshaled into JSON:
```go
evt json.RawMessage, ctx *runtime.Context) (*CustomType, error) { ... }
```
Also, if your CustomType satisfies the [Marshaler interface](https://golang.org/pkg/encoding/json/#Marshaler) then it will be automatically processed by the shim.
So I advocate on wrapping/modifying your protobuf type to implement this interface.

**Comment by ashinohara** [comment]
@fsenart Thanks for the quick response, I will give that a try!
