### ISSUE TITLE
Hosting dynamic golang web application in lambda

### ISSUE THREAD

**Issue by dtenenba** [eawsy/aws-lambda-go-shim#31]
So how would you host a dynamic web application written in golang, in AWS Lambda?
Could this be done with existing golang web frameworks? See this [analagous project for python](https://github.com/Miserlou/Zappa). 

A first step would be the ability to return content types other than JSON (html, images, etc). Is that possible?

**Comment by fsenart** [comment]
Hi @dtenenba,

Your wish is my command :smiley: 

You can use [eawsy/aws-lambda-go-net](https://github.com/eawsy/aws-lambda-go-net) and API Gateway Proxy mode with any golang web framework.
