### ISSUE TITLE
Is there an example to use Go to write API Gateway Custom Authorizer?

### ISSUE THREAD

**Issue by sunfmin** [eawsy/aws-lambda-go-shim#32]
https://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html

Saw examples in node.js and python. Not sure how it maps to Go with this package.

**Comment by fsenart** [comment]
Hi @sunfmin,

A custom authorizer is nothing more than a regular Lambda which is configured for being called by API Gateway for authorization. Looking at the link you provide you can easily translate the python code to Go. Please let me know if you need assistance for this part. 

PS: For general purpose web APIs with API Gateway we also provide [eawsy/aws-lambda-go-net](https://github.com/eawsy/aws-lambda-go-net).

**Comment by sunfmin** [comment]
It would be nice if this package could provide standard convenient struct definations to write Authorizers?

**Comment by fsenart** [comment]
@sunfmin it's a good idea, but I think https://github.com/eawsy/aws-lambda-go-net/tree/master/_example would be a better place. 
Have you succeeded in creating your authorizer? Can you make a pull request to the other repo? do you need us to provide this example?

**Comment by sunfmin** [comment]
I haven't succeeded yet. I am appreciated if you guys provide this example.

**Comment by fsenart** [comment]
@sunfmin yes for sure. It's 1h20 AM here in :fr:  :smile: so if its ok for you I will do the necessary tomorrow :wink:.

**Comment by lsuss** [comment]
Hi @sunfmin,

Really sorry for the delay, we were so busy :disappointed: 

Here is the exact translation of the link you've provided and it works with the shim. As stated in the doc, this is not a production ready example and is provided for the purpose of the example. Feel free to modify it to suit your needs:

```go
package main

import (
	"errors"
	"strings"

	"github.com/eawsy/aws-lambda-go-core/service/lambda/runtime"
)

type Statement struct {
	Action   string
	Effect   string
	Resource string
}

type PolicyDocument struct {
	Version   string
	Statement []*Statement
}

type Context struct {
	StringKey  string
	NumberKey  int64
	BooleanKey bool
}

type AuthResponse struct {
	PrincipalId    string
	PolicyDocument *PolicyDocument
	Context        *Context
}

func generatePolicy(principalId string, effect string, resource string) *AuthResponse {
	authResponse := &AuthResponse{}

	authResponse.PrincipalId = principalId
	if len(effect) > 0 && len(resource) > 0 {
		policyDocument := &PolicyDocument{}
		policyDocument.Version = "2012-10-17" // default version

		statementOne := &Statement{}
		statementOne.Action = "execute-api:Invoke" // default action
		statementOne.Effect = effect
		statementOne.Resource = resource

		policyDocument.Statement = append(policyDocument.Statement, statementOne)

		authResponse.PolicyDocument = policyDocument
	}

	// Can optionally return a context object of your choosing.
	authResponse.Context.StringKey = "stringval"
	authResponse.Context.NumberKey = 123
	authResponse.Context.BooleanKey = true

	return authResponse
}

type Authorizer struct {
	AuthorizationToken string
	MethodArn          string
	Type               string
}

// Handle provides an API Gateway Custom Authorizers.
// This is not a production code and is just provided as an example.
//
// Please refer to the full documentation for more information:
// https://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html
func Handle(evt *Authorizer, ctx *runtime.Context) (*AuthResponse, error) {
	switch token := strings.ToLower(evt.AuthorizationToken); token {
	case "allow":
		return generatePolicy("user", "Allow", evt.MethodArn), nil
	case "deny":
		return generatePolicy("user", "Deny", evt.MethodArn), nil
	case "unauthorized":
		return nil, errors.New("Unauthorized") // Return a 401 Unauthorized response
	default:
		return nil, errors.New("Error: Invalid token")
	}
}
```

**Comment by sunfmin** [comment]
Thanks a lots

**Comment by tbueno** [comment]
Since Google keeps bringing people like me to this discussion I think it is worth to contribute to the answer by saying that the `struct`s needed for building a valid `AuthResponse` are available and AWS Lambda Go library. Look for [APIGatewayCustomAuthorizerResponse ](https://github.com/aws/aws-lambda-go/blob/master/events/apigw.go#L106) in their source code. With that you don't need to definr the structs yourself.

**Comment by dthuering** [comment]
There is also an example using the types from the library:
https://github.com/aws/aws-lambda-go/blob/master/events/README_ApiGatewayCustomAuthorizer.md
