### ISSUE TITLE
Builds failing since the last image push

### ISSUE THREAD

**Issue by danielrife** [eawsy/aws-lambda-go-shim#36]
I'm getting ```Unable to find image 'eawsy/aws-lambda-go-shim:latest' locally
latest: Pulling from eawsy/aws-lambda-go-shim
Status: Downloaded newer image for eawsy/aws-lambda-go-shim:latest
lambda.go:17:2: cannot find package "github.com/eawsy/aws-lambda-go-core/service/lambda/runtime" in any of:
	/usr/local/go/src/github.com/eawsy/aws-lambda-go-core/service/lambda/runtime (from $GOROOT)
	/root/go/src/github.com/eawsy/aws-lambda-go-core/service/lambda/runtime (from $GOPATH)```
using the latest image.  No problems before that.

**Comment by danielrife** [comment]
Seems like the last success we had was 9 days ago.  Sha was the last successful build that worked. 37dda5fddfd77f0c5eb977b0faddf033e3b016ec

**Comment by fsenart** [comment]
Have you also updated your makefile to the latest version?

**Comment by danielrife** [comment]
I missed that, thanks for the help
