### ISSUE TITLE
Problem with running code in lambda 

### ISSUE THREAD

**Issue by EvgenKostenko** [eawsy/aws-lambda-go-shim#44]
On my local tests with amazon Linux container everything fine and runs and works. But when I deploy it to the lambda I got:

`
invalid character 'ó' looking for beginning of value: SyntaxError
Traceback (most recent call last):
File "runtime/proxy.py", line 44, in _handle
SyntaxError: invalid character 'ó' looking for beginning of value
`

**Comment by fsenart** [comment]
Hi @EvgenKostenko,
Can you please provide the output of the following command:
`docker run --rm eawsy/aws-lambda-go-shim version` 
along with the content of the handler you try to execute or any further info in order to be able to assist you and find what's going wrong.

**Comment by fsenart** [comment]
And please double check you use Python 2.7 as Lambda runtime.

**Comment by EvgenKostenko** [comment]
'
docker run --rm eawsy/aws-lambda-go-shim version
2017-11-15T22:48:08Z
'

<img width="952" alt="screen shot 2017-11-17 at 2 39 30 pm" src="https://user-images.githubusercontent.com/9476950/32947743-2f37a332-cba5-11e7-8ae3-214d0778d150.png">

**Comment by fsenart** [comment]
Can you please provide the code you try to execute. And confirm you use the project's Makefile without any modification, so you only do `make` to generate your handler.zip.

**Comment by fsenart** [comment]
As the examples provided int the README, etc work out of the box I need to spot the difference in your process.

**Comment by fsenart** [comment]
I'm assuming this issue is resolved. Please reopen and comment if otherwise.
