### ISSUE TITLE
How to access req/resp?

### ISSUE THREAD

**Issue by keynan** [eawsy/aws-lambda-go-shim#52]
In the event I'd like to return something sensible instead of JSON. Like an HTML/UI, or a fast marshal/unmarshal format such as PROTOBUF.

**Comment by fsenart** [comment]
Hi @keynan, 

AWS Lambda waits for a JSON response. So you cannot return other stuff. For your use case, one immediate solution may be to embed your response into a simple JSON serializable object: 

```go
map[string]interface{}{
  "HTML": `
    <body>
    </body>
  `,
}
```
