### ISSUE TITLE
Make file errors

### ISSUE THREAD

**Issue by nextdimension** [eawsy/aws-lambda-go-shim#9]
The instructions do not work

docker: Error response from daemon: invalid volume spec ":/tmp": invalid volume specification: ':/tmp'.
See 'docker run --help'.
Makefile:33: recipe for target 'all' failed
make: *** [all] Error 125

I chaged the make file "$(PWD):/tmp" to "$PWD:/tmp" and then I get this error

make: *** No rule to make target `_all'.  Stop.
Makefile:33: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fsenart** [comment]
Hi @nextdimension,

As the issue is highly related to your development environment. Can you please provide more information about the context (os, failing test, etc.).

**Comment by nextdimension** [comment]
@fsenart Hi,

I'm running linux, docker works fine, go is@version 1.8 and is working fine.
I simply followed the instructions on your main page.
I used your example go file, and your example  make file. 
I followed your instructions to the letter. 

When I use "make" the error I posted above occurs. What else do you want to know? my go installation is standard and all the environment PATHS are correctly setup.

**Comment by fsenart** [comment]
Can you please replace all reference of `$(PWD)` with `$(CURDIR)` in your `Makefile`. In seems that the later is more portable. If it's ok for you, I will update the repo with this modification.

**Comment by nextdimension** [comment]
Thank you, that did it

**Comment by fsenart** [comment]
:wink:
